-- subjects 테이블 개선 및 시간표 테이블 생성
-- 이 마이그레이션의 내용은 이미 프로덕션 DB에 존재함
-- - subjects 테이블의 grade, performance_ratio, written_ratio 컬럼
-- - schedules 테이블
-- 따라서 이 마이그레이션은 건너뜀

-- 참고: 다음이 이미 존재함
-- ALTER TABLE subjects ADD COLUMN grade INTEGER;
-- ALTER TABLE subjects ADD COLUMN performance_ratio INTEGER DEFAULT 40;
-- ALTER TABLE subjects ADD COLUMN written_ratio INTEGER DEFAULT 60;
-- CREATE TABLE IF NOT EXISTS schedules (...);
